// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import FlashController from "./flash_controller.js"
application.register("flash", FlashController)

import RedirectController from "./redirect_controller.js"
application.register("redirect", RedirectController)
